platform :"ios", "9.0"
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxMKMapView_Example' do
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod "RxMKMapView", :path => "../"
end

target 'RxMKMapView_Tests' do
  inherit! :search_paths
  pod "RxMKMapView", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.new_shell_script_build_phase.shell_script = "mkdir -p $PODS_CONFIGURATION_BUILD_DIR/#{target.name}"
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
