source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def common
    pod 'RxSwift', '~> 3.0.0-beta.1'
    pod 'RxCocoa', '~> 3.0.0-beta.1'
    pod "RxMKMapView", :path => "../"
end


target 'RxMKMapView_Example' do
  common
end

target 'RxMKMapView_Tests' do
  common
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'
  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'master'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
