platform :"ios", "8.0"
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxMKMapView_Example' do
  pod "RxMKMapView", :path => "../"
end

target 'RxMKMapView_Tests' do
  inherit! :search_paths
  pod "RxMKMapView", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end

