version: 2
jobs:
  build:
    working_directory: ~/RxSwiftCommunity/RxMKMapView
    parallelism: 1
    shell: /bin/bash --login
    environment:
      LANG: en_US.UTF-8
    macos:
      xcode: '10.0.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: 
          name: Bootstrap Carthage
          command: scripts/bootstrap-if-needed.sh
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - Carthage
      - run:
          name: Run Tests
          command: set -o pipefail && xcodebuild -workspace 'Example/RxMKMapView.xcworkspace' -scheme 'RxMKMapView-Example' -configuration 'Debug' -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator build test | xcpretty -c --test
      - run:
          name: Build Framework Workspace
          command: set -o pipefail && xcodebuild -workspace 'RxMKMapView.xcworkspace' -scheme 'RxMKMapView' -configuration 'Debug' -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator build | xcpretty -c
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: /tmp/xcode-test-artifcats
