version: 2
jobs:
  build:
    working_directory: ~/RxSwiftCommunity/RxMKMapView
    parallelism: 1
    shell: /bin/bash --login -o pipefail
    environment:
      LANG: en_US.UTF-8
    macos:
      xcode: '10.0.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run:
          name: Create artifacts paths
          command: mkdir test-results ; mkdir /tmp/xcode-test-artifacts
      - run: 
          name: Bootstrap Carthage
          command: scripts/bootstrap-if-needed.sh
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --project-directory=Example/
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - Carthage
      - run:
          name: Run Tests
          command: xcodebuild -workspace 'Example/RxMKMapView.xcworkspace' -scheme 'RxMKMapView-Example' -configuration 'Debug' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= -destination 'platform=iOS Simulator,name=iPhone 8' clean build test | tee '/tmp/xcode-test-artifacts/tests.log' | xcpretty --color --no-utf -r junit -o 'test-results/test.xml'
      - run:
          name: Build Framework Workspace
          command: xcodebuild -workspace 'RxMKMapView.xcworkspace' -scheme 'RxMKMapView' -configuration 'Debug' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= -destination 'platform=iOS Simulator,name=iPhone 8' clean build | tee '/tmp/xcode-test-artifacts/build.log' | xcpretty -c
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: /tmp/xcode-test-artifacts
